
on:
  push:
    branches:
    - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Invoke workflow in another repo with inputs
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: build-project
        repo: ${{ secrets.REPO_NAME }}
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        ref: new-structure
